#!/usr/bin/env python
# coding=utf-8

import os
import re
class filepath(object):
    def __init__(self):
      self.all_file_name=[]

    def get_all_path(self):
        c=os.getcwd()

        for fname in os.listdir(c):
            d=len(re.split('\.',fname))
            if re.split('\.',fname)[d-1]!='xls':
                pass
            else:
                file_name= c + '\\' + fname
                self.all_file_name.append(file_name)
        all_file_name=self.all_file_name
        print all_file_name
        return all_file_name












